pipeline:
  build:
    image: onaio/android:steps-app
    commands:
      - id
      - java -version
      - ./gradlew --version
      - ./gradlew clean build
      - ./gradlew test
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      event: [push, tag] 
